### ISSUE TITLE
Shouldn't the algorithm use np.argmax to find biggest jump in brightness?

### ISSUE THREAD

**Issue by rybak** [hate5six/hate5sync#2]
Please help me understand, because I got very confused by this part of the README.md (which corresponds to [lines 37-41 of the script](https://github.com/hate5six/hate5sync/blob/a345689f78a90f8ca13fc789ea49395d57c5d8f0/hate5sync.py#L37-L41)):

> We could look for the max brightness value, but quick tests indicate that finding the max change in brightness is more accurate. It makes sense: if you look at the above plot the peak isn't a sharp point, it spikes up then increases for a few frames before dropping down. We care about the initial jump. For each consecutive brightness values we'll compute the successive differences, then find the frame that contained the biggest jump:
> 
> ```
> pairs_bright = list(((b-a) for a,b in zip(brightness, brightness[1:])))
> peak_video = np.argmin(pairs_bright)
> ```

The prose says "biggest jump", but the code seems to look for the biggest _fall_. So then I thought that I didn't know what the list `brightness` stored, so I went back:

> We use open-cv to convert each frame to the LAB colorspace. All we care about the L channel, which captures lightness (intensity). L ends up being a matrix the size of the video frame (1920x1080). We normalize it so each value in the matrix is between 0-1. Then we compute the average value of that normalized matrix to get the average brightness of that image. Store that in a list called <b>brightness</b> and repeat the process on the next frame.

Per [Wikipedia article on Lab color space](https://en.wikipedia.org/wiki/Lab_color_space):

> The lightness value, L\*, also referred to as "Lstar," defines black at 0 and white at 100.

And the graph from the README seems to correspond to the notation black at 0.0 and white at 1.0 (not 100 because normalized):

![image](https://user-images.githubusercontent.com/624072/164643303-a2d51f6f-ece7-4e3d-b50f-33c13b401aaa.png)

I even tried running some numbers, similar to the graph in python repl myself:

```
>>> import numpy as np
>>> brightness=[0.92, 0.91, 0.92, 0.91, 0.93, 0.91, 0.91, 0.91, 0.91, 1.0, 1.01, 1.02, 0.91, 0.92, 0.92, 0.88, 0.88, 0.92, 0.92, 0.92 ]
>>> pairs_bright = list(((b-a) for a,b in zip(brightness, brightness[1:])))
>>> np.argmin(pairs_bright)
11
>>> np.argmax(pairs_bright)
8
```

`argmax` returns the index of where the jump from 0.91 to 1.0 happens and `argmin` returns the index of where the drop from 1.02 to 0.91 happens.

So my question is: shouldn't the algorithm use `np.argmax` to find, quote, "the biggest jump"?

**Comment by hate5six** [comment]
Intuitively you're right, but I believe things get weird when you start accounting for video compression and sensor noise. Consider the following. The flash occurs at frame 134 with a brightness value of 0.846. Even prior to the flash the brightness is non-zero because of sensor noise in the camera compounded by video compression. The flash is still visible at frames 135 and 136 but to a slightly lesser degree and then the screen is "black" by frame 137. I'm saying "black" because there's still noise in the image and it's not true blackness. 

![issue2_demo](https://user-images.githubusercontent.com/3986906/164724666-36f88380-c04f-4635-a341-f9d64550bb6c.png)

Your correct observation is that the jump to frame 138 is actually much larger. So what's happening?

Here are the frame by frame brightness values and deltas. I've used Photoshop to accentuate the contrast/brightness to demonstrate what the compression is doing:
![frame133](https://user-images.githubusercontent.com/3986906/164725611-c7ef9875-e64f-4947-8dac-09bbeb2d7470.jpg)
![frame134](https://user-images.githubusercontent.com/3986906/164725613-d96af119-32dd-4207-8c97-a6d9f7f8908a.jpg)
![frame135](https://user-images.githubusercontent.com/3986906/164725616-d807a510-f861-4101-b5cd-0e1d4cf46faf.jpg)
![frame136](https://user-images.githubusercontent.com/3986906/164725618-9ea07049-c083-4ce4-b095-09ac34c69e37.jpg)
![frame137](https://user-images.githubusercontent.com/3986906/164725619-0df69ba6-1286-4b5c-9b2c-d6d71c691afb.jpg)
![frame138](https://user-images.githubusercontent.com/3986906/164725621-4a331014-1439-4c63-8dd3-e64c827b7eb8.jpg)

Frame 133: no flash yet, noise/compression creates a brightness level of 0.621
Frame 134: flash comes on and brightness spikes, delta=0.225
Frame 135: flash is starting to turn off, less of the image is white, delta=-0.361
Frame 136: no change, delta=0
Frame 137: flash is completely off but the noise/compression is much lower where the flash existed in frames 135/136, delta =-0.347
Frame 138: noise/compression is now back to around its baseline which is BRIGHTER than when the flash turned off in Frame 137, delta=0.449

So the reason we see a bigger jump after the flash turns off has to do with the noise floor and how the compression handles sudden transitions from white->black.

**Comment by rybak** [comment]
Ok, you've clearly thought about the script a lot and you've convinced me that the code is correct. My question however, wasn't about the intricate details of signal processing. It was about the (perceived by me) discrepancy between the wording in README—"biggest jump"—and the code—`argmin`. To my mind, the word "jump" means _upwards_ movement. But code that calls `argmin` is searching for the biggest _downwards_ movement. Does it make sense?

**Comment by hate5six** [comment]
Got it. argmin was being used early on for an edge case. Switching to np.argmax in the latest commit for readability
